/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crawler_naver_news;

public class App {

    public static void main(String[] args) {
        Crawler crawler = new Crawler();
        crawler.run();
    }
}
