/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crawler_naver_news;

public class App {

    public static void main(String[] args) {
        Scheduler scheduler = new Scheduler();
        scheduler.run();
    }
}
